version: '3'

services:
  # MongoDB for development
  mongo:
    container_name: invtree_mongo
    image: mongo
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongodb:/data/db
      
  mongo-express:
    container_name: invtree_mongo_express
    image: mongo-express
    ports:
      - 9000:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
  
networks:
  invtree-network:
    driver: bridge

volumes:
  mongodb: